[package]
name = "fswww"
version = "0.1.0"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2018"
default-run = "fswww"

[profile.release]
debug = 0
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
#strip = true #enable this once it gets stabilized -- literally next cargo version

[dependencies]
smithay-client-toolkit = "0.15"
image = "0.23"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_warn"]}
simplelog = "^0.11.1"
fork = "0.1"
structopt = {version = "0.3", default-features = true}
nix = "0.23"

[dev-dependencies]
assert_cmd = "2.0"

[[test]]
name = "cmdline_test"
harness = false
