[package]
name = "fswww"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay-client-toolkit = "0.15"
image = "0.23"
log = "0.4"
env_logger = "0.9"
nix = "0.23"
tempfile = "3.2"
