[package]
name = "fswww"
version = "0.1.0"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2018"

[profile.release]
debug = 0
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
#strip = "symbols" #enable this once it gets stabilized -- literally next rust version, I think

[profile.bench]
debug = 1

[dependencies]
smithay-client-toolkit = "0.15"
image = "0.24"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
simplelog = "0.11"
fork = "0.1"
structopt = {version = "0.3", default-features = true}
hex = "0.4"
lz4_flex = {version = "0.9" , default-features = false}

[dev-dependencies]
assert_cmd = "2.0"
rand = "0.8"

[[test]]
name = "cmdline_test"
harness = false
