[package]
name = "fswww"
version = "0.1.0"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2018"

[profile.release]
debug = 0
lto = true
opt-level = 3
codegen-units = 1
panic = "abort" # stack unwinding is mostly useless since the user won't be able to see it during normal operation
#strip = "symbols" #enable this once it gets stabilized -- literally next rust version, I think

[profile.bench]
debug = 1

[dependencies]
smithay-client-toolkit = "0.15"
image = "0.24"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
simplelog = "0.11"
fork = "0.1"
clap = {version = "3.0.14", features = ["derive", "wrap_help"]}
hex = "0.4"
lz4_flex = {version = "0.9" , default-features = false}
serde = {version = "1.0", features = [ "derive" ]}
bincode = "1.3"

[dev-dependencies]
assert_cmd = "2.0"
rand = "0.8"

[build-dependencies]
clap = "3.0.14"
clap_complete = "3.0.6"
hex = "0.4"

[[test]]
name = "cmdline_test"
harness = false
